name: 'dbt_databricks_cicd'
version: '2.0.0'
profile: 'dbt_databricks_cicd'

model-paths: ["dbt_databricks_cicd/models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_databricks_cicd:
    raw:
      sqlserver:
        +enabled: "{{ target.name == 'sqlserver' }}"  
    staging:
      sqlserver:
        +enabled: "{{ target.name == 'sqlserver' }}"
      databricks:
        +enabled: "{{ target.name == 'databricks' }}"
    mart:
      sqlserver:
        +enabled: "{{ target.name == 'sqlserver' }}"
      databricks:
        +enabled: "{{ target.name == 'databricks' }}"




