version: 2

sources:
  - name: sqlserver
    database: MY_DB
    schema: dbo
    tables:
      - name: ecommerce
        description: Tabela de vendas do e-commerce

        # Teste global da estrutura da tabela:
        tests:
          - assert_source_structure:
              expected_columns:
                - name: Category
                  data_type: varchar
                - name: Discount
                  data_type: int
                - name: Final_Price
                  data_type: float
                - name: Payment_Method
                  data_type: varchar
                - name: Price
                  data_type: float
                - name: Product_ID
                  data_type: varchar
                - name: Purchase_Date
                  data_type: date
                - name: User_ID
                  data_type: varchar

        # Testes individuais por coluna:
        columns:
          - name: User_ID
            description: Identificador unico do cliente
            tests:
              - not_null

          - name: Product_ID
            description: Identificador unico do produto
            tests:
              - not_null

          - name: Category
            description: Categoria do produto
            tests:
              - not_null

          - name: Price
            description: Preco original do produto em rupias
            tests:
              - not_null

          - name: Discount
            description: Percentual de desconto aplicado
            tests:
              - not_null

          - name: Final_Price
            description: Preco final apos o desconto
            tests:
              - not_null

          - name: Payment_Method
            description: Forma de pagamento utilizada na compra
            tests:
              - not_null
              - accepted_values:
                  values: ['Credit Card', 'Net Banking', 'UPI', 'Debit Card', 'Cash on Delivery']

          - name: Purchase_Date
            description: Data da compra
            tests:
              - not_null