name: dbt CI/CD

on:
  push:
    branches: [ main ]  # roda somente na branch main
  pull_request:         # opcional: roda também em PRs

jobs:
  dbt-databricks:
    name: Run dbt in Databricks
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DBT_TARGET: ${{ secrets.DBT_TARGET }}
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dbt and dependencies
      run: |
        pip install dbt-databricks

    - name: Create dbt profile dynamically
      run: |
        mkdir -p ~/.dbt
        cat <<EOF > ~/.dbt/profiles.yml
dbt_databricks_cicd:
  target: $DBT_TARGET
  outputs:
    $DBT_TARGET:
      type: databricks
      method: token
      host: $DATABRICKS_HOST
      token: $DATABRICKS_TOKEN
      schema: $DBT_SCHEMA
      catalog: hive_metastore
      http_path: $DATABRICKS_HTTP_PATH
      threads: 4
      connect_timeout: 30
EOF

    name: Show profiles.yml
    run: |
      cat ~/.dbt/profiles.yml

    name: Run dbt deps
    run: |
      
      dbt deps

    name: Run dbt build
    run: |
      
      dbt build --target $DBT_TARGET

    name: Run dbt tests
    run: |
      
      dbt test --target $DBT_TARGET
